In [35]:
import pickle
import json
import numpy as np

In [36]:
with open(r'artifacts/model.pkl','rb') as file:
    model = pickle.load(file)
    
with open(r'artifacts/scaler.pkl','rb') as file:
    scaler = pickle.load(file)
    
with open(r'artifacts/model_data.json','r') as file:
    data = json.load(file)

In [37]:
model

DecisionTreeClassifier(ccp_alpha=9.088086276232383e-05, random_state=7)

In [38]:
scaler

StandardScaler()

In [39]:
data

{'features': ['no_of_adults',
  'no_of_children',
  'no_of_weekend_nights',
  'no_of_week_nights',
  'type_of_meal_plan',
  'required_car_parking_space',
  'room_type_reserved',
  'lead_time',
  'arrival_year',
  'arrival_month',
  'arrival_date',
  'repeated_guest',
  'no_of_previous_cancellations',
  'no_of_previous_bookings_not_canceled',
  'avg_price_per_room',
  'no_of_special_requests',
  'market_segment_type_Aviation',
  'market_segment_type_Complementary',
  'market_segment_type_Corporate',
  'market_segment_type_Offline',
  'market_segment_type_Online'],
 'type_of_meal_plan': {'Meal Plan 1': 1,
  'Not Selected': 0,
  'Meal Plan 2': 2,
  'Meal Plan 3': 3},
 'room_type_reserved': {'Room_Type 1': 1,
  'Room_Type 4': 4,
  'Room_Type 6': 6,
  'Room_Type 2': 2,
  'Room_Type 5': 5,
  'Room_Type 7': 7,
  'Room_Type 3': 3}}

In [40]:
test_array = np.zeros(model.n_features_in_)
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

### test data

In [41]:
no_of_adults = 2.0
no_of_children = 0.0
no_of_weekend_nights = 1.0
no_of_week_nights = 2.0
type_of_meal_plan = 1.0
required_car_parking_space = 0.0
room_type_reserved = 1.0
lead_time = 224.0
arrival_year = 2017.0
arrival_month = 10.0
arrival_date = 2.0
repeated_guest = 0.0
no_of_previous_cancellations = 0.0
no_of_previous_bookings_not_canceled = 0.0
avg_price_per_room = 65.0
no_of_special_requests = 0.0
market_segment_type_Aviation = 0.0
market_segment_type_Complementary = 0.0
market_segment_type_Corporate = 0.0
market_segment_type_Offline = 1.0
market_segment_type_Online = 0.0

In [42]:
test_array[0] = no_of_adults
test_array[1] = no_of_children
test_array[2] = no_of_weekend_nights
test_array[3] = no_of_week_nights
test_array[4] = type_of_meal_plan
test_array[5] = required_car_parking_space
test_array[6] = data['room_type_reserved'][room_type_reserved]
test_array[7] = lead_time
test_array[8] = arrival_year
test_array[9] = arrival_month
test_array[10] = arrival_date
test_array[11] = repeated_guest
test_array[12] = no_of_previous_cancellations
test_array[13] = no_of_previous_bookings_not_canceled
test_array[14] = avg_price_per_room
test_array[15] = no_of_special_requests
#index = data['features'].index(data[''])


KeyError: 1.0

In [43]:
data

{'features': ['no_of_adults',
  'no_of_children',
  'no_of_weekend_nights',
  'no_of_week_nights',
  'type_of_meal_plan',
  'required_car_parking_space',
  'room_type_reserved',
  'lead_time',
  'arrival_year',
  'arrival_month',
  'arrival_date',
  'repeated_guest',
  'no_of_previous_cancellations',
  'no_of_previous_bookings_not_canceled',
  'avg_price_per_room',
  'no_of_special_requests',
  'market_segment_type_Aviation',
  'market_segment_type_Complementary',
  'market_segment_type_Corporate',
  'market_segment_type_Offline',
  'market_segment_type_Online'],
 'type_of_meal_plan': {'Meal Plan 1': 1,
  'Not Selected': 0,
  'Meal Plan 2': 2,
  'Meal Plan 3': 3},
 'room_type_reserved': {'Room_Type 1': 1,
  'Room_Type 4': 4,
  'Room_Type 6': 6,
  'Room_Type 2': 2,
  'Room_Type 5': 5,
  'Room_Type 7': 7,
  'Room_Type 3': 3}}

In [44]:
test_array

array([2., 0., 1., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [45]:
no_of_adults = 2
no_of_children = 0
no_of_weekend_nights = 1
no_of_week_nights = 2
type_of_meal_plan = 'Meal Plan 2'
required_car_parking_space = 0
room_type_reserved = 'Room_Type 3'
lead_time = 224
arrival_year = 2017
arrival_month = 10
arrival_date = 2
market_segment_type = 'Online'
repeated_guest = 0
no_of_previous_cancellations = 0
no_of_previous_bookings_not_canceled = 0
avg_price_per_room = 65.0
no_of_special_requests = 0

In [46]:
test_array[0] = no_of_adults
test_array[1] = no_of_children
test_array[2] = no_of_weekend_nights
test_array[3] = no_of_week_nights
test_array[4] = data['type_of_meal_plan'][type_of_meal_plan]
test_array[5] = required_car_parking_space
test_array[6] = data['room_type_reserved'][room_type_reserved]
test_array[7] = lead_time
test_array[8] = arrival_year
test_array[9] = arrival_month
test_array[10] = arrival_date
test_array[11] = repeated_guest
test_array[12] = no_of_previous_cancellations
test_array[13] = no_of_previous_bookings_not_canceled
test_array[14] = avg_price_per_room
test_array[15] = no_of_special_requests

ind = data['features'].index('market_segment_type_'+market_segment_type)
test_array[ind] = 1

In [47]:
test_array

array([2.000e+00, 0.000e+00, 1.000e+00, 2.000e+00, 2.000e+00, 0.000e+00,
       3.000e+00, 2.240e+02, 2.017e+03, 1.000e+01, 2.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 6.500e+01, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00])

In [48]:
scaled_array = scaler.transform([test_array])

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [49]:
scaled_array

array([[ 0.30055965, -0.26543511,  0.22233699, -0.14489385,  2.18673111,
        -0.17881927,  0.92233216,  1.62147452, -2.13746929,  0.83924152,
        -1.55566209, -0.16220995, -0.09153802, -0.12982006, -1.19852419,
        -0.79479096, -0.05880319, -0.10438497, -0.24264534, -0.63945446,
         0.75008974]])

In [50]:
if model.predict(scaled_array)[0] == 1:
    print("Not cancelled")
else:
    print("Canceled")

Canceled


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
